// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OsuRussianRep.Context;

#nullable disable

namespace OsuRussianRep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121190653_AddedOsuIdAndProfileUrlToChatUserByWhois")]
    partial class AddedOsuIdAndProfileUrlToChatUserByWhois
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OsuRussianRep.Models.ChatStatics.IngestOffset", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint");

                    b.HasKey("Day");

                    b.ToTable("IngestOffsets", (string)null);
                });

            modelBuilder.Entity("OsuRussianRep.Models.ChatStatics.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("WordScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Lemma")
                        .IsUnique();

                    b.ToTable("Words", (string)null);
                });

            modelBuilder.Entity("OsuRussianRep.Models.ChatStatics.WordDay", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.Property<long>("Cnt")
                        .HasColumnType("bigint");

                    b.HasKey("Day", "WordId");

                    b.HasIndex("Day");

                    b.HasIndex("WordId");

                    b.ToTable("WordDays", (string)null);
                });

            modelBuilder.Entity("OsuRussianRep.Models.ChatStatics.WordUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.Property<long>("Cnt")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "WordId");

                    b.HasIndex("UserId");

                    b.HasIndex("WordId");

                    b.ToTable("WordUsers", (string)null);
                });

            modelBuilder.Entity("OsuRussianRep.Models.ChatUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastMessageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastRepNickname")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRepTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAddRep")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedWordRate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsuProfileUrl")
                        .HasColumnType("text");

                    b.Property<long?>("OsuUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Reputation")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("ChatUsers");
                });

            modelBuilder.Entity("OsuRussianRep.Models.Message", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Seq"));

                    b.Property<string>("ChatChannel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Seq");

                    b.HasIndex("Date");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ChatChannel", "Date");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("OsuRussianRep.Models.ChatStatics.WordDay", b =>
                {
                    b.HasOne("OsuRussianRep.Models.ChatStatics.Word", "Word")
                        .WithMany("Days")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("OsuRussianRep.Models.ChatStatics.WordUser", b =>
                {
                    b.HasOne("OsuRussianRep.Models.ChatUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OsuRussianRep.Models.ChatStatics.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("OsuRussianRep.Models.Message", b =>
                {
                    b.HasOne("OsuRussianRep.Models.ChatUser", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OsuRussianRep.Models.ChatStatics.Word", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("OsuRussianRep.Models.ChatUser", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
